// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JF
{
	/// <summary>
	/// 
	/// </summary>
	public class EpisodeInfo
	{
		public Episode data { get; set; }
	}
}
