// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JF
{
	/// <summary>
	/// 
	/// </summary>
	public class Episode
	{
		public int id { get; set; }
		public int airedSeason { get; set; }
		public int airedSeasonID { get; set; }
		public int airedEpisodeNumber { get; set; }
		public string episodeName { get; set; }
		public string firstAired { get; set; }
		public IList<string> guestStars { get; set; }
		public string director { get; set; }
		public IList<string> directors { get; set; }
		public IList<string> writers { get; set; }
		public string overview { get; set; }
		public Language language { get; set; }
		public string productionCode { get; set; }
		public string showUrl { get; set; }
		public int? lastUpdated { get; set; }
		public string dvdDiscid { get; set; }
		public int? dvdSeason { get; set; }
		public double? dvdEpisodeNumber { get; set; }
		public object dvdChapter { get; set; }
		public int? absoluteNumber { get; set; }
		public string filename { get; set; }
		public int seriesId { get; set; }
		public int? lastUpdatedBy { get; set; }
		public object airsAfterSeason { get; set; }
		public int? airsBeforeSeason { get; set; }
		public int? airsBeforeEpisode { get; set; }
		public int? thumbAuthor { get; set; }
		public string thumbAdded { get; set; }
		public string thumbWidth { get; set; }
		public string thumbHeight { get; set; }
		public string imdbId { get; set; }
		public double siteRating { get; set; }
		public int? siteRatingCount { get; set; }
	}
}
