// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JF
{
	/// <summary>
	/// 
	/// </summary>
    public class Episodes
    {
        public Links links { get; set; }
        public IList<Episode> data { get; set; }
        public Errors errors { get; set; }
    }
}
