// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JF
{
	/// <summary>
	/// 
	/// </summary>
    public class Links
    {
        public int first { get; set; }
        public int last { get; set; }
        public int? next { get; set; }
        public int? prev { get; set; }
    }
}
