// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator


namespace JF
{
	/// <summary>
	/// 
	/// </summary>
	public class Logon
	{
		#region Propriétés publiques
		public string apikey { get; set; }
		public string username { get; set; }
		public string userkey { get; set; }
		#endregion
	}
}
