// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JF
{
	/// <summary>
	/// 
	/// </summary>
    public class Series
    {
        public IList<Serie> data { get; set; }
    }
}
